build:
  cuda_version: "12.1.1"
  python_packages:
    - accelerate==1.8.0
    - transformers==4.52.4
    - inferless==0.2.15
    - pydantic==2.11.7
    - pillow==11.2.1
  run:
    - "pip install torch==2.6.0  torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cu126"
